### PR TITLE
Make OrdMap::range not implement ExactSizedIterator

### LINKED ISSUE #84: OrdMap::range returns an ExactSizeIterator with the wrong size hint
Sample code:

```rust
use imbl::OrdMap;

fn main() {
    let mut map = OrdMap::new();
    map.insert(1, "one");
    map.insert(2, "two");
    map.insert(5, "five");
    let iter = map.range(2..5);
    println!("{}", iter.len()); // prints 3
    println!("{:?}", iter.collect::<Vec<_>>()) // prints [(2, "two")]
}
```

`OrdMap::range` returns an iterator that claims to know the number of items it will iterate over, but it just uses `self.size` which is the size of the entire map. This causes `size_hint` to return the wrong value (in this case `(3, Some(3))`). Furthermore, `Iter` implements `ExactSizeIterator` which is also wrong in this case.

`OrdMap::range` should probably return a different iterator wrapper. I notice the underlying RangedIter implements a conservative `size_hint` that returns `(0, None)` (it could probably return `(0, Some(self.remaining))` though).

### PR DESCRIPTION
**Pull request by jneem**
Fixes #84

### CODE REVIEW

File: src/ord/map.rs [hunk 1]
```diff
@@ -1906,6 +1908,46 @@ where
 
 impl<'a, K, V> ExactSizeIterator for Iter<'a, K, V> where (K, V): 'a + BTreeValue {}
 
+/// An iterator over a range of key/value pairs in a map.
+pub struct RangeIter<'a, K, V> {
+    // This uses a `RangedIter` internally, but we only construct it when the range is
+    // full, meaning that we can override `size_hint` and implement `ExactSizeIterator`.
```
Comment (jplatte) [inline src/ord/map.rs:1914]: This is the same comment as for `Iter`, but there is no size hint override or `impl ExactSizeIterator` for this new type.

**Review by jplatte — APPROVED** [review]

**Comment by goffrie** [comment]
Should `RangedIter` be made private now?

**Comment by jneem** [comment]
Yes, good point. And I took the opportunity to rename `RangeIter -> RangedIter` so that the naming is more consistent with `OrdSet`.

**Review by goffrie — APPROVED** [review]
